---
title: "csaw"
output: 
    html_document:
        keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```

## BAM Files


```{r, message=FALSE, warning=FALSE}
library(csaw)
library(edgeR)

my_ChIP <- "K36"
my_control <- "INP"

bam.files <- list.files("../BAM/", pattern = ".bam$")
bam.files <- bam.files[grep(paste(my_ChIP,my_control,sep="|"), bam.files)]
bam.files.path <- file.path("../BAM/", bam.files)

my_samples <- gsub("_[G,A,T,C].*","",bam.files)

print(bam.files)
print(my_samples)
```

## Counting

```{r, message=FALSE, warning=FALSE, fig.align="center" }
param <- readParam(minq=0, BPPARAM = MulticoreParam(4))

win.data <- windowCounts(bam.files.path, param=param, width=250, ext=150)
bin.data <- windowCounts(bam.files.path, bin=TRUE, param=param, width=10000)

saveRDS(win.data, file = paste(my_ChIP,"win.data.rds", sep="."))
saveRDS(bin.data, file = paste(my_ChIP,"bin.data.rds", sep="."))

win.data

metadata(win.data)

colData(win.data)

rowRanges(win.data)

head(assay(win.data))
```

```{r, message=FALSE, warning=FALSE, fig.align="center" }

ChIP.win.data <- win.data[,!(grepl("INP", bam.files))]
INP.win.data <- win.data[,grep("INP", bam.files)]

ChIP.bin.data <- bin.data[,!(grepl("INP", bam.files))]
INP.bin.data <- bin.data[,grep("INP", bam.files)]

```

## Filtering


```{r, message=FALSE, warning=FALSE, fig.align="center" }
filter.stat <- filterWindows(data =       ChIP.win.data, 
                             background = INP.win.data, 
                             type = "control", 
                             prior.count = 5, 
                             norm.fac = list(ChIP.bin.data, INP.bin.data))
min.fc <- 2
keep <- filter.stat$filter > log2(min.fc)

ChIP.filt.data <- ChIP.win.data[keep,]

saveRDS(ChIP.filt.data, paste(my_ChIP,"filt.data.rds", sep="."))

summary(keep)


library(RColorBrewer)
my_colors <- brewer.pal(9,"Set1")

par(mfrow=c(1,2),  oma=c(3,0,0,0),mar=c(5,4,4,1), mgp = c(2.5,1,0),
    cex=1, cex.axis=1, cex.lab=1.25, cex.main=1.5)


plot(density(filter.stat$back.abundances), xlim=c(-1,5), 
     type="l", col=my_colors[9], lwd=3,
     xlab="log2 CPM", main="Pre-Filtering")
lines(density(filter.stat$abundances), col=my_colors[5], lwd=3)

plot(density(filter.stat$back.abundances[keep]), xlim=c(-1,5), 
     type="l", col=my_colors[9], lwd=3,
     xlab="log2 CPM", main="Post-Filtering")
lines(density(filter.stat$abundances[keep]), col=my_colors[5], lwd=3)

par(fig = c(0, 1, 0, 1), oma = c(0, 0, 0, 0), mar = c(0, 0, 0, 0), new = TRUE)

plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n")
legend(-0.33,-0.75, legend =  c("ChIP","Input"),
       xpd = TRUE, horiz = TRUE, inset = c(2, 0), bty = "n", pch = 19, col = my_colors[c(5,9)], cex = 1.25)


par(mfrow=c(1,1), oma=c(3,0,0,0),mar=c(5,4,4,1), mgp = c(2.5,1,0),
    cex=1, cex.axis=1, cex.lab=1.25, cex.main=1.5)


my_region <- 1:2000
keep_region <- keep[my_region]

ylim <- ceiling(max(filter.stat$abundances[my_region]))*1.2

plot(start(rowRanges(win.data))[my_region], 
     filter.stat$abundances[my_region],
     type="l", col=my_colors[5], lwd=2, ylim=c(1,ylim),
     xlab="Coordinates", ylab="log2 CPM", main = "Example Region")

xx <- c(start(rowRanges(win.data))[my_region], rev(start(rowRanges(win.data))[my_region]))
yy <- c(rep(0,length(my_region)), rev(filter.stat$abundances[my_region]))
polygon(xx, yy, col=my_colors[5], lty = 0)
lines(filter.stat$back.abundances[my_region],type="l", col=my_colors[9], lwd=2)

xx <- c(start(rowRanges(win.data))[my_region], rev(start(rowRanges(win.data))[my_region]))
yy <- c(rep(0,length(my_region)), rev(filter.stat$back.abundances[my_region]))
polygon(xx, yy, col=my_colors[9], lty = 0)

xx <- c(start(rowRanges(win.data))[my_region], rev(start(rowRanges(win.data))[my_region]))
yy <- c(rep(0,length(my_region)), rev(keep_region*(ylim/20)))+(ylim*0.95)
polygon(xx, yy, col=my_colors[5], lty = 0)

par(fig = c(0, 1, 0, 1), oma = c(0, 0, 0, 0), mar = c(0, 0, 0, 0), new = TRUE)

plot(0, 0, type = "n", bty = "n", xaxt = "n", yaxt = "n")
legend(-0.33,-0.75, legend =  c("ChIP","Input"),
       xpd = TRUE, horiz = TRUE, inset = c(2, 0), bty = "n", pch = 19, col = my_colors[c(5,9)], cex = 1.25)

```

## Trended Bias

```{r, message=FALSE, warning=FALSE, fig.align="center"}
par(mfrow=c(1,2), oma=c(3,0,0,0),mar=c(5,4,4,1), mgp = c(2.5,1,0),
    cex=1, cex.axis=1, cex.lab=1.25, cex.main=1.5)

win.ab <- aveLogCPM(asDGEList(ChIP.filt.data))
adjc <- log2(assay(ChIP.filt.data)+0.5)
logfc <- adjc[,1] - adjc[,4]
smoothScatter(win.ab, logfc, ylim=c(-4, 4), xlim=c(1, 5),
    xlab="Average abundance", ylab="Log-fold change")


offsets <- normOffsets(ChIP.filt.data, type="loess")
norm.adjc <- adjc - offsets/log(2)
norm.fc <- norm.adjc[,1]-norm.adjc[,4]
smoothScatter(win.ab, norm.fc, ylim=c(-4, 4), xlim=c(1, 5),
    xlab="Average abundance", ylab="Log-fold change")
```

## Estimate Variability

```{r, message=FALSE, warning=FALSE, fig.align="center"}
stage <- factor(gsub("[A-B]_.*","", bam.files[!(grepl("INP", bam.files))]))
design <- model.matrix(~0+stage)
colnames(design) <- levels(stage)
design

y <- asDGEList(ChIP.filt.data)
y <- scaleOffset(y, offsets)
y <- estimateDisp(y, design)
summary(y$trended.dispersion)

fit <- glmQLFit(y, design, robust=TRUE)

par(mfrow=c(1,2), oma=c(3,0,0,0),mar=c(5,4,4,1), mgp = c(2.5,1,0),
    cex=1, cex.axis=1, cex.lab=1.25, cex.main=1.5)

plotBCV(y)

plotQLDisp(fit)

summary(fit$df.prior)
```



## Differential Test


```{r, message=FALSE, warning=FALSE}
contrast <- makeContrasts(E11-E03, levels=design)
res <- glmQLFTest(fit, contrast=contrast)
head(res$table)


merged <- mergeWindows(rowRanges(ChIP.filt.data), tol=100, max.width=5000)
tabcom <- combineTests(merged$id, res$table)

head(tabcom)

is.sig <- tabcom$FDR <= 0.05
summary(is.sig)

table(tabcom$direction[is.sig])


tabbest <- getBestTest(merged$id, res$table)
head(tabbest)
```




## Region Annotation

```{r, message=FALSE, warning=FALSE}
out.ranges <- merged$region

elementMetadata(out.ranges) <- data.frame(tabcom,
    best.pos=mid(ranges(rowRanges(ChIP.filt.data[tabbest$best]))),
    best.logFC=tabbest$logFC,
    ave.logFC=sapply(1:nrow(tabcom), function(i){mean(res$table$logFC[merged$id == i]) })
    )


library(org.Dm.eg.db)
library(TxDb.Dmelanogaster.UCSC.dm6.ensGene)

my_genes <- genes(TxDb.Dmelanogaster.UCSC.dm6.ensGene)
my_genes <- my_genes[seqnames(my_genes) %in% unique(seqnames(out.ranges))]

out.ranges <- out.ranges[seqnames(out.ranges) %in% unique(seqnames(my_genes))]

mid.ranges <- makeGRangesFromDataFrame(data.frame(chr=seqnames(out.ranges),
                                                   start=mid(ranges(out.ranges)),
                                                   end=mid(ranges(out.ranges))))

my_nearest <- nearest(mid.ranges,my_genes)
out.ranges$gene_id <- my_genes[my_nearest]$gene_id

out.ranges$gene_name <- mapIds(org.Dm.eg.db, out.ranges$gene_id, "SYMBOL", keytype="ENSEMBL", multiVals="first")

saveRDS(out.ranges, paste(my_ChIP,"results.rds", sep="."))

out.ranges
```



